apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-connector
  namespace: default  # or another namespace if you prefer
  labels:
      app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      restartPolicy: Always
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel
          - --no-autoupdate
          - run
          - --token
          - eyJhIjoiMWEwYmI2Y2E4ZTIyODBmMDk5NTEzNzgwZjBhNmVhMGUiLCJ0IjoiMDczNjg1YjctMzUwMC00MmJhLTg2OWItNDQ2NDNjNjUzODRmIiwicyI6Ik56QTNaR1ppTXprdFlUUTFaaTAwTkdFMkxUZzVZakV0WVdOak5EYzBNelZsTXpabSJ9
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"