apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulting-website
  labels:
    app: consulting-website
spec:
  replicas: 2  # You can increase/decrease based on traffic
  selector:
    matchLabels:
      app: consulting-website
  template:
    metadata:
      labels:
        app: consulting-website
    spec:
      containers:
      - name: consulting-website
        image: consulting-website:latest  # <-- Change this
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20